name: sample-dockerfile
services:
- dockerfile_path: DockerfileProd
  source_dir: ./gui
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 3000
  name: sample-gui

- dockerfile_path: Dockerfile
  source_dir: ./
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 8001
  routes:
    - path: /api
  name: sample-backend
  
envs:
- key: POSTGRES_USER
  value: superagi
- key: POSTGRES_PASSWORD
  value: password
- key: POSTGRES_DB
  value: super_agi_main
- key: POSTGRES_URL
  value: ${superagi--postgres.POSTGRES_URL}
#- key: REDIS_URL
#  value: ${superagi--redis.REDIS_URL}

databases:
- name: superagi--postgres
  db_user: superagi
  db_name: super_agi_main
  engine: PG
  # db_password: password
  
#- name: superagi--redis
#  engine: REDIS
#  production: true
#  cluster_name: superagi--redis