name: sample-dockerfile
services:
- dockerfile_path: DockerfileProd
  source_dir: ./gui
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 3000
  name: sample-gui

- dockerfile_path: Dockerfile
  source_dir: ./
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 8001
  routes:
    - path: /api
  name: sample-backend
  
envs:
- key: DB_USER
  value: superagi
- key: DB_PASSWORD
  value: ${super-agi-main.PASSWORD}
- key: DB_NAME
  value: super-agi-main
- key: POSTGRES_URL
  value: ${super-AGI-MAIN.DATABASE_URL}
#- key: REDIS_URL
#  value: ${superagi--redis.REDIS_URL}

databases:
- name: super-agi-main
  db_user: superagi
  db_name: super-agi-main
  engine: PG
  # db_password: password
  
#- name: superagi--redis
#  engine: REDIS
#  production: true
#  cluster_name: superagi--redis