name: superagi
services:
- dockerfile_path: ./gui/DockerfileProd
  source_dir: ./gui
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 3000
  name: sample-gui

- dockerfile_path: Dockerfile
  source_dir: ./
  github:
    branch: main
    deploy_on_push: true
    repo: TransformerOptimus/SuperAGI
  http_port: 8001
  routes:
    - path: /api
  name: sample-backend

#envs:
#- key: DB_USER
#  value: superagi
#- key: DB_PASSWORD
#  value: password
#- key: DB_NAME
#  value: super-agi-main
#- key: POSTGRES_URL
#  value: ${super-agi-main.DATABASE_URL}
##- key: REDIS_URL
##  value: ${superagi--redis.REDIS_URL}
#
#databases:
#- name: super-agi-main
#  db_name: super-agi-main
#  engine: PG

#- name: superagi--redis
#  engine: REDIS
#  production: true
#  cluster_name: superagi--redis